### ISSUE TITLE
Doesn't install in windows

### ISSUE THREAD

**Issue by almogon** [strongloop/modern-syslog#20]
Hello, i try install modern-syslog but i have this error:
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "modern-syslog"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code EBADPLATFORM

npm ERR! notsup Unsupported
npm ERR! notsup Not compatible with your operating system or architecture: modern-syslog@1.1.4
npm ERR! notsup Valid OS:    !win32
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64

Modern-syslog doesn't work in windows ??

Thanks

**Comment by rmg** [comment]
More accurately, Windows does not support syslog :-(

This module is a "simple" wrapper for the standard [`syslog(3)`](http://pubs.opengroup.org/onlinepubs/009695399/functions/syslog.html) interface that is available on UNIX-style OSes (Linux, BSDs, Darwin/macOS) as part of POSIX.

**Comment by cawoodm** [comment]
> More accurately, Windows does not support syslog :-(

This is incorrect: windows does support syslog and the module `node-syslog` works cross platform. So it *could* work on windows with some adaptation.
