### ISSUE TITLE
No trace?

### ISSUE THREAD

**Issue by basickarl** [strongloop/modern-syslog#25]
I see that there is no trace option.

Is there a particular reason behind this?

**Comment by sam-github** [comment]
what is a trace option?

FYI, https://linux.die.net/man/3/syslog, the word "trace" does not occur.

**Comment by basickarl** [comment]
@sam-github This thread has a few answers and explanations: https://stackoverflow.com/questions/2031163/when-to-use-the-different-log-levels

In short however trace is a very *very* fine tuned way of seeing how your code is executed. It creates a *substantial* amount of logs and is never recommended to be turned on in a production environment due to that.

**Comment by sam-github** [comment]
There is no TRACE log level in OS X (https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man3/syslog.3.html#//apple_ref/doc/man/3/syslog) or linux (https://linux.die.net/man/3/syslog).

Perhaps its not clear, this module wraps the unix syscall facility. If a level is not supported by that facility, this module can't add it (the facility is not extendable).
