### ISSUE TITLE
Module not working with nodejs version 9.6.1

### ISSUE THREAD

**Issue by sipjsdev** [strongloop/modern-syslog#26]
This module is not working with nodejs version v9.6.1. 
I did npm rebuild after getting error NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 59. Please try re-compiling or re-installing.

Got below error while rebuilding

make: Entering directory `/home/amalhotra/v8/node_modules/modern-syslog/build'
  CXX(target) Release/obj.target/core/core.o
../core.cc: In member function 'virtual void {anonymous}::Worker::HandleOKCallback()':
../core.cc:34:39: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated (declared at ../../nan/nan.h:1568) [-Wdeprecated-declarations]
                 callback->Call(0, NULL);
                                       ^
../core.cc: In function 'Nan::NAN_METHOD_RETURN_TYPE {anonymous}::SysLog(Nan::NAN_METHOD_ARGS_TYPE)':
../core.cc:97:31: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated (declared at ../../nan/nan.h:1568) [-Wdeprecated-declarations]
         callback->Call(0, NULL);
                               ^
  SOLINK_MODULE(target) Release/obj.target/core.node
  COPY Release/core.node

**Comment by sam-github** [comment]
Not errors, warnings, the build succeeded.

**Comment by sipjsdev** [comment]
Thanks it is working now.After doing npm rebuild again it worked.
