### ISSUE TITLE
Provide .d.ts file for TypeScript

### ISSUE THREAD

**Issue by fgm** [strongloop/modern-syslog#28]
Currently trying to convert my filog package using modern-syslog to TypeScript, and modern-syslog is the only dependency which doesn't either have builtin .d.ts files or an entry for @types/modern-syslog.

Either solution would help anyone trying to use modern-syslog with TypeScript.

**Comment by fgm** [comment]
I added a version which appears to work for me on https://github.com/fgm/modern-syslog/tree/28-typescript : would you be interesting in checking it out and possibly taking a PR ? Or should I submit it to https://github.com/DefinitelyTyped/DefinitelyTyped ?

**Comment by sam-github** [comment]
@rmg thoughts? I'm not keen to maintain mappings for a language I never use, but then again, the API is not likely to change, so there shouldn't be much maintenance.

**Comment by rmg** [comment]
I think it makes more sense to keep it in this repo.

**Comment by fgm** [comment]
@rmg Thanks for answering. In the meantime, I received other feedback suggesting it might be better to submit it to DefinitelyTyped instead if the package is not supposed to be converted to TypeScript itself, which is unlikely since it is in C and not in JS. And it would avoid your having to care for a file you don't use.

**Comment by rmg** [comment]
I figured it would be easier to keep it in sync if it was in-repo, but in this case the API is highly unlikely to change much, if at all, so I suppose it doesn't really matter much.

**Comment by sam-github** [comment]
The exposed API is partly javascript, and I've no interest in rewriting it as ts.

Anyhow, if you provide one as @rmg suggests, I'll accept, if you put in definitely typed, that's OK too.

**Comment by fgm** [comment]
Thanks for your answers.
