### ISSUE TITLE
supports iojs 3?

### ISSUE THREAD

**Issue by Dexus** [strongloop/modern-syslog#7]
I get build fails with 3.2.0 and 3.3.0...

**Comment by rmg** [comment]
@Dexus what errors are you seeing? It is building fine for me on OS X and on Linux under our CI.

**Comment by Dexus** [comment]
see https://travis-ci.org/Dexus/Haraka/jobs/78639406

**Comment by rmg** [comment]
The version of gcc in that build is 4.6, but the version of v8 that is used in iojs-3+ requires gcc-4.8 or newer due to the use of C++11 features.

Example: https://github.com/nodejs/nan/commit/05ed3b67d9e755592f696b4a41542657a90ab4b2

**Comment by rmg** [comment]
See 57fe2ac for a less noisy example than nan itself.

**Comment by Dexus** [comment]
:+1: perfect thank you for your fast clearing of the problem :)
