### ISSUE TITLE
no syslogs on FreeBSD

### ISSUE THREAD

**Issue by Dexus** [strongloop/modern-syslog#8]
```
$ uname -prs
FreeBSD 10.1-RELEASE-p16 amd64
$ node -v
v0.10.40
```
can you please check what wrong?

**Comment by msimerson** [comment]
tested on bare metal FreeBSD and a Docker with FreeBSD image.

**Comment by sam-github** [comment]
Hi, what is the issue you are trying to report? Is something not installing? What are you doing, and what is the output, and how do we reproduce?

FreeBSD in general certainly has [syslog](https://www.freebsd.org/cgi/man.cgi?query=syslog&apropos=0&sektion=0&manpath=FreeBSD+10.2-RELEASE&arch=default&format=html), perhaps you are running a stripped down image/distro with an incomplete C library?

**Comment by Dexus** [comment]
Hi,

I have a complete new webserver installed but don't get any log with the module in syslogs... With the node-syslog or the strong-fork-syslog logs are in the syslog.

So there are must a bug or im wrong? 

Von meinem iPhone gesendet

**Comment by sam-github** [comment]
All the syslog modules just call `syslog()`, its hard to see what's different.Without some idea of what you are seeing I don't know, and can't fix anything.

For example, I don't know if the module didn't compile, if it compiled but failed at runtime, or ran, but you can't find the logs, or something else entirely. I don't even know which of our tools you are using, or what you are sending to syslog (`--metrics`? `--log`?).

> What are you doing, and what is the output, and how do we reproduce?

**Comment by Dexus** [comment]
No build errors as i can see. And the tests don't write to syslogs. On debian and ubuntu there are no problems.



Von meinem iPhone gesendet

**Comment by Dexus** [comment]
Our PR thats tests and shows the Bug: baudehlo/Haraka/pull/1145

**Comment by rmg** [comment]
Bad news, it worked for me _and_ all the tests pass..

```
vagrant@:~/node_modules/modern-syslog %	npm test

> modern-syslog@1.1.0 test /home/vagrant/node_modules/modern-syslog
> tap test/test-*.js

test/test-compat.js ................................... 8/8
test/test-core.js ................................... 14/14
test/test-openlog.js .June[854]: Hi, June
Leonie: Hi, Leonie
test/test-openlog.js .................................. 1/1
test/test-setmask.js ................................ 32/32
test/test-stream.js ................................. 14/14
test/test-syslog.js ................................. 15/15
total ............................................... 84/84

  84 passing (2s)

  ok
vagrant@:~/node_modules/modern-syslog %	uname -prs
FreeBSD 10.2-STABLE amd64
vagrant@:~/node_modules/modern-syslog %	node -v
v0.12.7
```

**Comment by Dexus** [comment]
and what is in your syslog written?

**Comment by msimerson** [comment]
Two things:

1. you used node 0.12 vs 0.10 (potential difference)
2. Tests pass for us too, but did it actually write log entries in /var/log/maillog or /var/log/messages?

**Comment by rmg** [comment]
It wrote to `/var/log/messages`, I just didn't show it because I did it from the repl. I'm cooking up a test script now so I can try to break it.

**Comment by rmg** [comment]
@msimerson where did you get your node binaries from? I just did `pkg install node` and v0.12.7 is what it gave me.

**Comment by msimerson** [comment]
````
pkg install node010
````

Which is the same thing as:
````
cd /usr/ports/www/node010 && make install clean
````

except faster. 

Matt

**Comment by msimerson** [comment]
FreeBSD pkg hint:

````
%	pkg search node
drupal6-nodewords-6.x.1.14
gstreamer-plugins-annodex-0.10.31_1,3
leafnode-1.11.11
munin-node-2.0.25_4
node-0.12.7
node-devel-0.11.16_2
node-thrift-0.9.1_1
node010-0.10.40
p5-Tree-DAG_Node-1.27
p5-Tree-Node-0.08_2
p5-WebService-Linode-0.28
p5-XML-Node-0.11_1
p5-XML-NodeFilter-0.01_1
xnodecor-0.1_2
````

**Comment by rmg** [comment]
Ended up just installing from a source tarball...
```
vagrant@:~ % uname -prs
FreeBSD 10.2-STABLE amd64
vagrant@:~ % ~/n/bin/node -v
v0.10.40
vagrant@:~ % ~/n/bin/node -e 'require("modern-syslog").error("modern-syslog FTW!");'
vagrant@:~ % tail -1 /var/log/messages
Sep 17 22:08:37  node: modern-syslog FTW!
```

**Comment by rmg** [comment]
FWIW, node-syslog and strong-fork-syslog are also working for me on v0.10.40.
